### ISSUE TITLE
Latest release virus detected

### ISSUE THREAD

**Issue by alrik11es** [DotModGroup/ColdWaters-DotMod#144]
Hi I tried to install the latest release. Antivirus detected possible malware. When I upload the DotModInstaller.exe file to VirusTotal I get this.

![imagen](https://user-images.githubusercontent.com/249844/216928126-96809d7f-4a99-421e-8efe-5213938c2616.png)

https://www.virustotal.com/gui/file/27b30f8ef8d292ea68221c50541aeb95068184f188cf69c400ca777666913ba6/detection

Can you please check it out?

**Comment by alrik11es** [comment]
I've double checked the code and JSGME.exe file seems fine. This DotModInstaller.exe is clearly unsecure. I've installed the mod with the python script that also seems secure.

**Comment by HobbitJack** [comment]
Known issue with the compiler used for the .exe. Nuitka, the compiler used, is often flagged in the loading stage due to its (and PyInstaller's) commonly being used in Python malware. The code itself is clean, and can be compiled to a .exe by the end user and run, though in many cases the compiled .exe will still be flagged for the same reasons mentioned above. This is, again, because we can't have nice things. Thanks, malware.

**Comment by alrik11es** [comment]
I've been documenting myself on that. Thanks for pointing me on the right direction. Well, maybe a small side-note in the project readme file could be interesting to notice this problem. Just tell the users how to install with python instead, works like a charm anyways. Closing the issue. Thanks, again. And nice mod.
