### ISSUE TITLE
Dotmod installer.exe have Trojan its my computer it’s detected  I reset PC 

### ISSUE THREAD

**Issue by kirov181** [DotModGroup/ColdWaters-DotMod#166]
I found a virus on my computer
Dodmodinstaller .exe have Trojan 
I was worried so I reset PC 😭

**Comment by HobbitJack** [comment]
This is a known issue with the installer, caused by the use of a Python compilation tool called Nuitka, which leads to false-positives from various malware suites. There's nothing we can do other than supply the source code so that anyone can view it and compile it he wishes.
Since the installer program is not working, you can instead complete a manual installation by copy-pasting the ColdWaters_Data folder from the download archive and putting it so that it merges with the ColdWaters_Data folder in your game. You will be asked to overwrite some files. Then, you can launch the game with the mod installed.
We are sorry for the inconvenience.
